Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 1152
      Handler: comr.br.school.reyfowemails.Handler
      CodeUri: /home/rafael/Downloads/reyfow-emails
      Runtime: java11
      Architectures:
        - x86_64